blueprint:
  name: Motion-Activated Light with Night Settings
  description: Turn on a light when motion is detected, with specific brightness for night hours.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    day_brightness:
      name: Day Brightness
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    night_brightness:
      name: Night Brightness
      default: 20
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    night_start_time:
      name: Night Start Time
      default: "22:00:00"
      selector:
        time: {}
    night_end_time:
      name: Night End Time
      default: "07:00:00"
      selector:
        time: {}
    no_motion_wait:
      name: Wait time
      description: Time to wait after last motion is detected before turning lights off.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

action:
  - alias: "Assign variables for template"
    variables:
      # We map inputs to variables here so the template can see them
      v_start: !input night_start_time
      v_end: !input night_end_time
      v_day_br: !input day_brightness
      v_night_br: !input night_brightness

  - alias: "Turn on light with calculated brightness"
    service: light.turn_on
    target: !input light_target
    data:
      brightness_pct: >
        {% set now_time = now().strftime('%H:%M:%S') %}
        {% if v_start < v_end %}
          {# Daytime window (e.g., 08:00 to 20:00) #}
          {{ v_night_br if v_start <= now_time <= v_end else v_day_br }}
        {% else %}
          {# Overnight window (e.g., 22:00 to 06:00) #}
          {{ v_night_br if now_time >= v_start or now_time <= v_end else v_day_br }}
        {% endif %}

  - alias: "Wait for motion to stop"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"

  - alias: "Wait for timeout"
    delay: !input no_motion_wait

  - alias: "Turn off light"
    service: light.turn_off
    target: !input light_target